<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/**
 * @var yii\web\View $this
 * @var app\models\Familia $model
 */
$this->title = 'Família ' . $model->label . '';
$this->params['breadcrumbs'][] = ['label' => 'Familias', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->label, 'url' => ['view', 'idFamilia' => $model->idFamilia]];
$this->params['breadcrumbs'][] = 'Detalhes';
?>
<div class="familia-view">

    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> Editar', ['update', 'idFamilia' => $model->idFamilia], ['class' => 'btn btn-info'])
        ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> Nova Família', ['create'], ['class' => 'btn
        btn-success']) ?>
    </p>

    <p class='pull-right'>
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> Lista', ['index'], ['class' => 'btn btn-default']) ?>
    </p><div class='clearfix'></div> 


    <h3>
        <?= $model->label ?>    </h3>


    <?php $this->beginBlock('app\models\Familia'); ?>

    <?php
    echo DetailView::widget([
        'model' => $model,
        'attributes' => [
            'idFamilia',
            'NomeCientifico',
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'idOrdem',
                'value' => ($model->getIdOrdem0()->one() ? Html::a($model->getIdOrdem0()->one()->label, ['ordem/view', 'idOrdem' => $model->getIdOrdem0()->one()->idOrdem,]) : '<span class="label label-warning">?</span>'),
            ],
            'Descricao:ntext',
        ],
    ]);
    ?>

    <hr/>

    <?php
    echo Html::a('<span class="glyphicon glyphicon-trash"></span> Deletar', ['delete', 'idFamilia' => $model->idFamilia], [
        'class' => 'btn btn-danger',
        'data-confirm' => Yii::t('app', 'Tem certeza que quer deletar esse item?'),
        'data-method' => 'post',
    ]);
    ?>

    <?php $this->endBlock(); ?>



    <?php $this->beginBlock('Generos'); ?>
    <p class='pull-right'>
        <?=
        \yii\helpers\Html::a(
                '<span class="glyphicon glyphicon-list"></span> Listar todos gêneros', ['genero/index'], ['class' => 'btn text-muted btn-xs']
        )
        ?>
        <?=
        \yii\helpers\Html::a(
                '<span class="glyphicon glyphicon-plus"></span> Novo Gênero', ['genero/create', 'Genero' => ['idFamilia' => $model->idFamilia]], ['class' => 'btn btn-success btn-xs']
        )
        ?>
    </p><div class='clearfix'></div>
    <?php Pjax::begin(['id' => 'pjax-Generos', 'linkSelector' => '#pjax-Generos ul.pagination a']) ?>
    <?=
    \yii\grid\GridView::widget([
        'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getGeneros(), 'pagination' => ['pageSize' => 10]]),
        'columns' => [ 'idGenero',
            'NomeCientifico',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update}',
                'contentOptions' => ['nowrap' => 'nowrap'],
                'urlCreator' => function($action, $model, $key, $index)
        {
            // using the column name as key, not mapping to 'id' like the standard generator
            $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
            $params[0] = 'genero' . '/' . $action;
            return \yii\helpers\Url::toRoute($params);
        },
                'buttons' => [
                ],
                'controller' => 'genero'
            ],]
    ]);
    ?>
    <?php Pjax::end() ?>
    <?php $this->endBlock() ?>


    <?=
    \yii\bootstrap\Tabs::widget(
            [
                'id' => 'relation-tabs',
                'encodeLabels' => false,
                'items' => [ [
                        'label' => '<span class="glyphicon glyphicon-asterisk"></span> Família',
                        'content' => $this->blocks['app\models\Familia'],
                        'active' => true,
                    ], [
                        'label' => '<small><span class="glyphicon glyphicon-paperclip"></span> Gêneros</small>',
                        'content' => $this->blocks['Generos'],
                        'active' => false,
                    ],]
            ]
    );
    ?></div>
