<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/**
 * @var yii\web\View $this
 * @var app\models\TipoDescritor $model
 */
$this->title = 'Tipo de Descritor: ' . $model->label . '';
$this->params['breadcrumbs'][] = ['label' => 'Tipos de Descritor', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->label, 'url' => ['view', 'idTipoDescritor' => $model->idTipoDescritor]];
$this->params['breadcrumbs'][] = 'Detalhes';
?>
<div class="tipo-descritor-view">

    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> Editar', ['update', 'idTipoDescritor' => $model->idTipoDescritor], ['class' => 'btn btn-info'])
        ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> Novo Tipo de Descritor', ['create'], ['class' => 'btn
        btn-success']) ?>
    </p>

    <p class='pull-right'>
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> Lista', ['index'], ['class' => 'btn btn-default']) ?>
    </p><div class='clearfix'></div> 


    <h3>
        <?= $model->label ?>    </h3>


    <?php $this->beginBlock('app\models\TipoDescritor'); ?>

    <?php
    echo DetailView::widget([
        'model' => $model,
        'attributes' => [
            'idTipoDescritor',
            'Tipo',
            'Descricao:ntext',
        ],
    ]);
    ?>

    <hr/>

    <?php
    echo Html::a('<span class="glyphicon glyphicon-trash"></span> Deletar', ['delete', 'idTipoDescritor' => $model->idTipoDescritor], [
        'class' => 'btn btn-danger',
        'data-confirm' => Yii::t('app', 'Tem certeza que quer deletar esse item?'),
        'data-method' => 'post',
    ]);
    ?>

    <?php $this->endBlock(); ?>



    <?php $this->beginBlock('Descritores'); ?>
    <p class='pull-right'>
        <?=
        \yii\helpers\Html::a(
                '<span class="glyphicon glyphicon-list"></span> Listar todos descritores', ['descritor/index'], ['class' => 'btn text-muted btn-xs']
        )
        ?>
        <?=
        \yii\helpers\Html::a(
                '<span class="glyphicon glyphicon-plus"></span> Novo Descritor', ['descritor/create', 'Descritor' => ['idTipoDescritor' => $model->idTipoDescritor]], ['class' => 'btn btn-success btn-xs']
        )
        ?>
    </p><div class='clearfix'></div>
    <?php Pjax::begin(['id' => 'pjax-Descritores', 'linkSelector' => '#pjax-Descritores ul.pagination a']) ?>
    <?=
    \yii\grid\GridView::widget([
        'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getDescritores(), 'pagination' => ['pageSize' => 10]]),
        'columns' => [ 'idDescritor',
            'Nome',
// generated by schmunk42\giiant\crud\providers\RelationProvider::columnFormat
            [
                "class" => yii\grid\DataColumn::className(),
                "attribute" => "idTipoDado",
                "value" => function($model)
                {
                    if ($rel = $model->getIdTipoDado0()->one())
                    {
                        return yii\helpers\Html::a($rel->label, ["tipo-dado/view", 'idTipoDado' => $rel->idTipoDado,], ["data-pjax" => 0]);
                    } else
                    {
                        return '';
                    }
                },
                        "format" => "raw",
                    ],
                    'Descricao:ntext',
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{view} {update}',
                        'contentOptions' => ['nowrap' => 'nowrap'],
                        'urlCreator' => function($action, $model, $key, $index)
                {
                    // using the column name as key, not mapping to 'id' like the standard generator
                    $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                    $params[0] = 'descritor' . '/' . $action;
                    return \yii\helpers\Url::toRoute($params);
                },
                        'buttons' => [
                        ],
                        'controller' => 'descritor'
                    ],]
            ]);
            ?>
            <?php Pjax::end() ?>
            <?php $this->endBlock() ?>


            <?=
            \yii\bootstrap\Tabs::widget(
                    [
                        'id' => 'relation-tabs',
                        'encodeLabels' => false,
                        'items' => [ [
                                'label' => '<span class="glyphicon glyphicon-asterisk"></span> TipoDescritor',
                                'content' => $this->blocks['app\models\TipoDescritor'],
                                'active' => true,
                            ], [
                                'label' => '<small><span class="glyphicon glyphicon-paperclip"></span> Descritores</small>',
                                'content' => $this->blocks['Descritores'],
                                'active' => false,
                            ],]
                    ]
            );
            ?></div>
