<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/**
 * @var yii\web\View $this
 * @var app\models\Descritor $model
 */
$this->title = 'Descritor ' . $model->label . '';
$this->params['breadcrumbs'][] = ['label' => 'Descritores', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->label, 'url' => ['view', 'idDescritor' => $model->idDescritor]];
$this->params['breadcrumbs'][] = 'Detalhes';
?>
<div class="descritor-view">

    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> Editar', ['update', 'idDescritor' => $model->idDescritor], ['class' => 'btn btn-info'])
        ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> Novo Descritor', ['create'], ['class' => 'btn
        btn-success']) ?>
    </p>

    <p class='pull-right'>
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> Lista', ['index'], ['class' => 'btn btn-default']) ?>
    </p><div class='clearfix'></div> 


    <h3>
        <?= $model->label ?>    </h3>


    <?php $this->beginBlock('app\models\Descritor'); ?>

    <?php
    echo DetailView::widget([
        'model' => $model,
        'attributes' => [
            'idDescritor',
            'Nome',
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'idTipoDado',
                'value' => ($model->getIdTipoDado0()->one() ? Html::a($model->getIdTipoDado0()->one()->label, ['tipo-dado/view', 'idTipoDado' => $model->getIdTipoDado0()->one()->idTipoDado,]) : '<span class="label label-warning">?</span>'),
            ],
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'idTipoDescritor',
                'value' => ($model->getIdTipoDescritor0()->one() ? Html::a($model->getIdTipoDescritor0()->one()->label, ['tipo-descritor/view', 'idTipoDescritor' => $model->getIdTipoDescritor0()->one()->idTipoDescritor,]) : '<span class="label label-warning">?</span>'),
            ],
            'Descricao:ntext',
        ],
    ]);
    ?>

    <hr/>

    <?php
    echo Html::a('<span class="glyphicon glyphicon-trash"></span> Deletar', ['delete', 'idDescritor' => $model->idDescritor], [
        'class' => 'btn btn-danger',
        'data-confirm' => Yii::t('app', 'Tem certeza que quer deletar esse item?'),
        'data-method' => 'post',
    ]);
    ?>

    <?php $this->endBlock(); ?>



    <?php $this->beginBlock('IdTipoOrganismos'); ?>
    <p class='pull-right'>
        <?=
        \yii\helpers\Html::a(
                '<span class="glyphicon glyphicon-list"></span> Listar todos os tipo de organismos', ['tipo-organismo/index'], ['class' => 'btn text-muted btn-xs']
        )
        ?>
        <?=
        \yii\helpers\Html::a(
                '<span class="glyphicon glyphicon-plus"></span> Novo Tipo de Organismo', ['tipo-organismo/create', 'IdTipoOrganismo' => ['idTipoOrganismo' => $model->idDescritor]], ['class' => 'btn btn-success btn-xs']
        )
        ?>
    </p><div class='clearfix'></div>
    <?php Pjax::begin(['id' => 'pjax-IdTipoOrganismos', 'linkSelector' => '#pjax-IdTipoOrganismos ul.pagination a']) ?>
    <?=
    \yii\grid\GridView::widget([
        'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getTipoOrganismoHasDescritores(), 'pagination' => ['pageSize' => 10]]),
        'columns' => [
            'idTipoOrganismo0.Nome',
            'idTipoOrganismo0.Descricao',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {delete}',
                'contentOptions' => ['nowrap' => 'nowrap'],
                'urlCreator' => function($action, $model, $key, $index)
        {
            // using the column name as key, not mapping to 'id' like the standard generator
            $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
            $params[0] = 'tipo-organismo-has-descritor' . '/' . $action;
            return \yii\helpers\Url::toRoute($params);
        },
                'buttons' => [
                    'delete' => function ($url, $model)
                    {
                        return Html::a('<span class="glyphicon glyphicon-remove"></span>', $url, [
                                    'class' => 'text-danger',
                                    'title' => Yii::t('yii', 'Remove'),
                                    'data-confirm' => Yii::t('yii', 'Are you sure you want to delete the related item?'),
                                    'data-method' => 'post',
                                    'data-pjax' => '0',
                        ]);
                    },
                            'view' => function ($url, $model)
                    {
                        return Html::a(
                                        '<span class="glyphicon glyphicon-cog"></span>', $url, [
                                    'data-title' => Yii::t('yii', 'View Pivot Record'),
                                    'data-toggle' => 'tooltip',
                                    'data-pjax' => '0',
                                    'class' => 'text-muted'
                                        ]
                        );
                    },
                        ],
                        'controller' => 'tipo-organismo-has-descritor'
                    ],]
            ]);
            ?>
            <?php Pjax::end() ?>
            <?php $this->endBlock() ?>


            <?=
            \yii\bootstrap\Tabs::widget(
                    [
                        'id' => 'relation-tabs',
                        'encodeLabels' => false,
                        'items' => [ [
                                'label' => '<span class="glyphicon glyphicon-asterisk"></span> Descritor',
                                'content' => $this->blocks['app\models\Descritor'],
                                'active' => true,
                            ], [
                                'label' => '<small><span class="glyphicon glyphicon-paperclip"></span> Tipo de organismos</small>',
                                'content' => $this->blocks['IdTipoOrganismos'],
                                'active' => false,
                            ],]
                    ]
            );
            ?></div>
