<?php

use yii\helpers\Html;
use yii\grid\GridView;

/**
* @var yii\web\View $this
* @var yii\data\ActiveDataProvider $dataProvider
* @var app\models\EspecieSearch $searchModel
*/

$this->title = 'Especies';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="especie-index">

    <?php //     echo $this->render('_search', ['model' =>$searchModel]);
    ?>

    <div class="clearfix">
        <p class="pull-left">
            <?= Html::a('<span class="glyphicon glyphicon-plus"></span> New Especie', ['create'], ['class' => 'btn btn-success']) ?>
        </p>

        <div class="pull-right">


                                                                                                            
            <?php 
            echo \yii\bootstrap\ButtonDropdown::widget(
                [
                    'id'       => 'giiant-relations',
                    'encodeLabel' => false,
                    'label'    => '<span class="glyphicon glyphicon-paperclip"></span> Relations',
                    'dropdown' => [
                        'options'      => [
                            'class' => 'dropdown-menu-right'
                        ],
                        'encodeLabels' => false,
                        'items'        => [
    [
        'label' => '<i class="glyphicon glyphicon-arrow-right"> Coleta Item</i>',
        'url' => [
            'coleta-item/index',
        ],
    ],
    [
        'label' => '<i class="glyphicon glyphicon-arrow-left"> Genero</i>',
        'url' => [
            'genero/index',
        ],
    ],
    [
        'label' => '<i class="glyphicon glyphicon-arrow-left"> Tipo Organismo</i>',
        'url' => [
            'tipo-organismo/index',
        ],
    ],
]                    ],
                ]
            );
            ?>        </div>
    </div>

            <?php echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
        
			'idEspecie',
			'NomeCientifico',
			'NomeComum',
			'Descricao:ntext',
			// generated by schmunk42\giiant\crud\providers\RelationProvider::columnFormat
[
            "class" => yii\grid\DataColumn::className(),
            "attribute" => "idGenero",
            "value" => function($model){
                if ($rel = $model->getIdGenero0()->one()) {
                    return yii\helpers\Html::a($rel->label,["genero/view", 'idGenero' => $rel->idGenero,],["data-pjax"=>0]);
                } else {
                    return '';
                }
            },
            "format" => "raw",
],
			// generated by schmunk42\giiant\crud\providers\RelationProvider::columnFormat
[
            "class" => yii\grid\DataColumn::className(),
            "attribute" => "idTipo_Organismo",
            "value" => function($model){
                if ($rel = $model->getIdTipoOrganismo0()->one()) {
                    return yii\helpers\Html::a($rel->label,["tipo-organismo/view", 'idTipoOrganismo' => $rel->idTipoOrganismo,],["data-pjax"=>0]);
                } else {
                    return '';
                }
            },
            "format" => "raw",
],
            [
                'class' => 'yii\grid\ActionColumn',
                'urlCreator' => function($action, $model, $key, $index) {
                    // using the column name as key, not mapping to 'id' like the standard generator
                    $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                    $params[0] = \Yii::$app->controller->id ? \Yii::$app->controller->id . '/' . $action : $action;
                    return \yii\helpers\Url::toRoute($params);
                },
                'contentOptions' => ['nowrap'=>'nowrap']
            ],
        ],
    ]); ?>
    
</div>
