<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/**
* @var yii\web\View $this
* @var app\models\Especie $model
*/

$this->title = 'Especie View ' . $model->idEspecie . '';
$this->params['breadcrumbs'][] = ['label' => 'Especies', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->label, 'url' => ['view', 'idEspecie' => $model->idEspecie]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="especie-view">

    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> Edit', ['update', 'idEspecie' => $model->idEspecie],
        ['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> New Especie', ['create'], ['class' => 'btn
        btn-success']) ?>
    </p>

        <p class='pull-right'>
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> List', ['index'], ['class'=>'btn btn-default']) ?>
    </p><div class='clearfix'></div> 

    
    <h3>
        <?= $model->label ?>    </h3>


    <?php $this->beginBlock('app\models\Especie'); ?>

    <?php echo DetailView::widget([
    'model' => $model,
    'attributes' => [
    			'idEspecie',
			'NomeCientifico',
			'NomeComum',
			'Descricao:ntext',
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
[
    'format'=>'html',
    'attribute'=>'idGenero',
    'value' => ($model->getIdGenero0()->one() ? Html::a($model->getIdGenero0()->one()->label, ['genero/view', 'idGenero' => $model->getIdGenero0()->one()->idGenero,]) : '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
[
    'format'=>'html',
    'attribute'=>'idTipo_Organismo',
    'value' => ($model->getIdTipoOrganismo0()->one() ? Html::a($model->getIdTipoOrganismo0()->one()->label, ['tipo-organismo/view', 'idTipoOrganismo' => $model->getIdTipoOrganismo0()->one()->idTipoOrganismo,]) : '<span class="label label-warning">?</span>'),
],
    ],
    ]); ?>

    <hr/>

    <?php echo Html::a('<span class="glyphicon glyphicon-trash"></span> Delete', ['delete', 'idEspecie' => $model->idEspecie],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => Yii::t('app', 'Are you sure to delete this item?'),
    'data-method' => 'post',
    ]); ?>

    <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('ColetaItems'); ?>
<p class='pull-right'>
  <?= \yii\helpers\Html::a(
            '<span class="glyphicon glyphicon-list"></span> List All Coleta Items',
            ['coleta-item/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= \yii\helpers\Html::a(
            '<span class="glyphicon glyphicon-plus"></span> New Coleta Item',
            ['coleta-item/create', 'ColetaItem'=>['idEspecie'=>$model->idEspecie]],
            ['class'=>'btn btn-success btn-xs']
        ) ?>
</p><div class='clearfix'></div>
<?php Pjax::begin(['id'=>'pjax-ColetaItems','linkSelector'=>'#pjax-ColetaItems ul.pagination a']) ?>
<?= \yii\grid\GridView::widget([
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getColetaItems(), 'pagination' => ['pageSize' => 10]]),
    'columns' => [			'idColetaItem',
// generated by schmunk42\giiant\crud\providers\RelationProvider::columnFormat
[
            "class" => yii\grid\DataColumn::className(),
            "attribute" => "idColeta",
            "value" => function($model){
                if ($rel = $model->getIdColeta0()->one()) {
                    return yii\helpers\Html::a($rel->label,["coleta/view", 'idColeta' => $rel->idColeta,],["data-pjax"=>0]);
                } else {
                    return '';
                }
            },
            "format" => "raw",
],
[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'coleta-item' . '/' . $action;
        return \yii\helpers\Url::toRoute($params);
    },
    'buttons'    => [
        
    ],
    'controller' => 'coleta-item'
],]
]);?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?=
    \yii\bootstrap\Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<span class="glyphicon glyphicon-asterisk"></span> Especie',
    'content' => $this->blocks['app\models\Especie'],
    'active'  => true,
],[
    'label'   => '<small><span class="glyphicon glyphicon-paperclip"></span> Coleta Items</small>',
    'content' => $this->blocks['ColetaItems'],
    'active'  => false,
], ]
                 ]
    );
    ?></div>
