<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/**
 * @var yii\web\View $this
 * @var app\models\Especie $model
 */
$this->title = 'Espécie ' . $model->label . '';
$this->params['breadcrumbs'][] = ['label' => 'Espécies', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->label, 'url' => ['view', 'idEspecie' => $model->idEspecie]];
$this->params['breadcrumbs'][] = 'Detalhes';
?>
<div class="especie-view">

    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> Editar', ['update', 'idEspecie' => $model->idEspecie], ['class' => 'btn btn-info'])
        ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> Nova Espécie', ['create'], ['class' => 'btn
        btn-success']) ?>
    </p>

    <p class='pull-right'>
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> Lista', ['index'], ['class' => 'btn btn-default']) ?>
    </p><div class='clearfix'></div> 


    <h3>
        <?= $model->label ?>    </h3>


    <?php $this->beginBlock('app\models\Especie'); ?>

    <?php
    echo DetailView::widget([
        'model' => $model,
        'attributes' => [
            'idEspecie',
            'NomeComum',
            'NomeCientifico',
            'Autor',
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'idGenero',
                'value' => ($model->getIdGenero0()->one() ? Html::a($model->getIdGenero0()->one()->label, ['genero/view', 'idGenero' => $model->getIdGenero0()->one()->idGenero,]) : '<span class="label label-warning">?</span>'),
            ],
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'idTipo_Organismo',
                'value' => ($model->getIdTipoOrganismo()->one() ? Html::a($model->getIdTipoOrganismo()->one()->label, ['tipo-organismo/view', 'idTipoOrganismo' => $model->getIdTipoOrganismo()->one()->idTipoOrganismo,]) : '<span class="label label-warning">?</span>'),
            ],
            'Descricao:ntext',
        ],
    ]);
    ?>

    <hr/>

    <?php
    echo Html::a('<span class="glyphicon glyphicon-trash"></span> Deletar', ['delete', 'idEspecie' => $model->idEspecie], [
        'class' => 'btn btn-danger',
        'data-confirm' => Yii::t('app', 'Tem certeza que quer deletar esse item?'),
        'data-method' => 'post',
    ]);
    ?>

    <?php $this->endBlock(); ?>




    <?=
    \yii\bootstrap\Tabs::widget(
            [
                'id' => 'relation-tabs',
                'encodeLabels' => false,
                'items' => [ [
                        'label' => '<span class="glyphicon glyphicon-asterisk"></span> Espécie',
                        'content' => $this->blocks['app\models\Especie'],
                        'active' => true,
                    ], ]
            ]
    );
    ?></div>
