<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/**
 * @var yii\web\View $this
 * @var app\models\Genero $model
 */
$this->title = 'Gênero ' . $model->label . '';
$this->params['breadcrumbs'][] = ['label' => 'Gêneros', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->label, 'url' => ['view', 'idGenero' => $model->idGenero]];
$this->params['breadcrumbs'][] = 'Detalhes';
?>
<div class="genero-view">

    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> Editar', ['update', 'idGenero' => $model->idGenero], ['class' => 'btn btn-info'])
        ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> Novo Gênero', ['create'], ['class' => 'btn
        btn-success']) ?>
    </p>

    <p class='pull-right'>
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> Lista', ['index'], ['class' => 'btn btn-default']) ?>
    </p><div class='clearfix'></div> 


    <h3>
        <?= $model->label ?>    </h3>


    <?php $this->beginBlock('app\models\Genero'); ?>

    <?php
    echo DetailView::widget([
        'model' => $model,
        'attributes' => [
            'idGenero',
            'NomeCientifico',
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'idFamilia',
                'value' => ($model->getIdFamilia0()->one() ? Html::a($model->getIdFamilia0()->one()->label, ['familia/view', 'idFamilia' => $model->getIdFamilia0()->one()->idFamilia,]) : '<span class="label label-warning">?</span>'),
            ],
            'Descricao:ntext',
        ],
    ]);
    ?>

    <hr/>

    <?php
    echo Html::a('<span class="glyphicon glyphicon-trash"></span> Deletar', ['delete', 'idGenero' => $model->idGenero], [
        'class' => 'btn btn-danger',
        'data-confirm' => Yii::t('app', 'Tem certeza que quer deletar esse item?'),
        'data-method' => 'post',
    ]);
    ?>

    <?php $this->endBlock(); ?>



    <?php $this->beginBlock('Especies'); ?>
    <p class='pull-right'>
        <?=
        \yii\helpers\Html::a(
                '<span class="glyphicon glyphicon-list"></span> Listar todas as espécies', ['especie/index'], ['class' => 'btn text-muted btn-xs']
        )
        ?>
        <?=
        \yii\helpers\Html::a(
                '<span class="glyphicon glyphicon-plus"></span> Nova Espécie', ['especie/create', 'Especie' => ['idGenero' => $model->idGenero]], ['class' => 'btn btn-success btn-xs']
        )
        ?>
    </p><div class='clearfix'></div>
    <?php Pjax::begin(['id' => 'pjax-Especies', 'linkSelector' => '#pjax-Especies ul.pagination a']) ?>
    <?=
    \yii\grid\GridView::widget([
        'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getEspecies(), 'pagination' => ['pageSize' => 10]]),
        'columns' => [ 'idEspecie',
            'NomeComum',
            'NomeCientifico',
// generated by schmunk42\giiant\crud\providers\RelationProvider::columnFormat
            [
                "class" => yii\grid\DataColumn::className(),
                "attribute" => "idTipo_Organismo",
                "value" => function($model)
                {
                    if ($rel = $model->getIdTipoOrganismo()->one())
                    {
                        return yii\helpers\Html::a($rel->label, ["tipo-organismo/view", 'idTipoOrganismo' => $rel->idTipoOrganismo,], ["data-pjax" => 0]);
                    } else
                    {
                        return '';
                    }
                },
                        "format" => "raw",
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{view} {update}',
                        'contentOptions' => ['nowrap' => 'nowrap'],
                        'urlCreator' => function($action, $model, $key, $index)
                {
                    // using the column name as key, not mapping to 'id' like the standard generator
                    $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                    $params[0] = 'especie' . '/' . $action;
                    return \yii\helpers\Url::toRoute($params);
                },
                        'buttons' => [
                        ],
                        'controller' => 'especie'
                    ],]
            ]);
            ?>
            <?php Pjax::end() ?>
            <?php $this->endBlock() ?>


            <?=
            \yii\bootstrap\Tabs::widget(
                    [
                        'id' => 'relation-tabs',
                        'encodeLabels' => false,
                        'items' => [ [
                                'label' => '<span class="glyphicon glyphicon-asterisk"></span> Gênero',
                                'content' => $this->blocks['app\models\Genero'],
                                'active' => true,
                            ], [
                                'label' => '<small><span class="glyphicon glyphicon-paperclip"></span> Espécies</small>',
                                'content' => $this->blocks['Especies'],
                                'active' => false,
                            ],]
                    ]
            );
            ?></div>
