INSERT INTO Ordem VALUES (1,'Accipitriformes','','',1),
	(2,'Anseriformes','','',1),
	(3,'Apodiformes ','','',1),
	(4,'Caprimulgiformes ','','',1),
	(5,'Cariamiformes ','','',1),
	(6,'Cathartiformes ','','',1),
	(7,'Charadriiformes ','','',1),
	(8,'Ciconiiformes ','','',1),
	(9,'Columbiformes ','','',1),
	(10,'Coraciiformes ','','',1),
	(11,'Cuculiformes ','','',1),
	(12,'Falconiformes ','','',1),
	(13,'Galbuliformes ','','',1),
	(14,'Galliformes','','',1),
	(15,'Gruiformes ','','',1),
	(16,'Passeriformes ','','',1),
	(17,'Pelecaniformes ','','',1),
	(18,'Phoenicopteriformes ','','',1),
	(19,'Piciformes ','','',1),
	(20,'Podicipediformes','','',1),
	(21,'Psittaciformes ','','',1),
	(22,'Strigiformes ','','',1),
	(23,'Struthioniformes','','',1),
	(24,'Tinamiformes','','',1),
	(25,'Trogoniformes ','','',1)