<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\web\JsExpression;

/**
 * @var yii\web\View $this
 * @var app\models\NaoIdentificado $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="nao-identificado-form">

    <?php $form = ActiveForm::begin(['layout' => 'horizontal', 'enableClientValidation' => false]); ?>

    <div class="">
        <?php echo $form->errorSummary($model); ?>
        <?php $this->beginBlock('main'); ?>

        <p>

            <?=
            $form->field($model, 'idPesquisadorIdentificacao')->widget(\app\widgets\Select2Active\Select2Active::classname(), [
                'pluginOptions' => [
                    'allowClear' => true,
                    'ajax' => [
                        'url' => yii\helpers\Url::to(["pesquisador/findpesquisador"]),
                        'dataType' => 'json',
                        'data' => new JsExpression('function(term,page) { return {pesquisador:term.term}; }'),
                        'results' => new JsExpression('function(data,page) { return {results:data.results}; }'),
                    ],
                    'initSelection' => true
                ],
            ]);
            ?>
            <?=
            $form->field($model, 'idTipoOrganismo')->widget(\app\widgets\Select2Active\Select2Active::classname(), [
                'pluginOptions' => [
                    'allowClear' => true,
                    'ajax' => [
                        'url' => yii\helpers\Url::to(["tipo-organismo/findtipoorganismo"]),
                        'dataType' => 'json',
                        'data' => new JsExpression('function(term,page) { return {nomeOrganismo:term.term}; }'),
                        'results' => new JsExpression('function(data,page) { return {results:data.results}; }'),
                    ],
                    'initSelection' => true
                ],
            ]);
            ?>
            <?=
            // generated by schmunk42\giiant\crud\providers\RelationProvider::activeField
            $form->field($model, 'idFilo')->dropDownList(
                    \yii\helpers\ArrayHelper::map(app\models\Filo::find()->all(), 'idFilo', 'label'), ['prompt' => 'Choose...']
            );
            ?>
            <?=
            // generated by schmunk42\giiant\crud\providers\RelationProvider::activeField
            $form->field($model, 'idOrdem')->dropDownList(
                    \yii\helpers\ArrayHelper::map(app\models\Ordem::find()->all(), 'idOrdem', 'label'), ['prompt' => 'Choose...']
            );
            ?>
            <?=
            // generated by schmunk42\giiant\crud\providers\RelationProvider::activeField
            $form->field($model, 'idFamilia')->dropDownList(
                    \yii\helpers\ArrayHelper::map(app\models\Familia::find()->all(), 'idFamilia', 'label'), ['prompt' => 'Choose...']
            );
            ?>
            <?=
            // generated by schmunk42\giiant\crud\providers\RelationProvider::activeField
            $form->field($model, 'idGenero')->dropDownList(
                    \yii\helpers\ArrayHelper::map(app\models\Genero::find()->all(), 'idGenero', 'label'), ['prompt' => 'Choose...']
            );
            ?>
            <?=
            // generated by schmunk42\giiant\crud\providers\RelationProvider::activeField
            $form->field($model, 'idEspecie')->dropDownList(
                    \yii\helpers\ArrayHelper::map(app\models\Especie::find()->all(), 'idEspecie', 'label'), ['prompt' => 'Choose...']
            );
            ?>
            <?=
            $form->field($model, 'Data_Registro')->widget(\app\widgets\DateTime\DateTimePicker::classname(), [
                'options' => ['class' => 'form-control'],
                'pluginOptions' => [
                    'autoclose' => true,
                    'todayHighlight' => true,
                ]
            ]);
            ?>
            <?=
            $form->field($model, 'Data_Identificacao')->widget(\app\widgets\DateTime\DateTimePicker::classname(), [
                'options' => ['class' => 'form-control'],
                'pluginOptions' => [
                    'autoclose' => true,
                    'todayHighlight' => true,
                ]
            ]);
            ?>
            <?= $form->field($model, 'MorfoEspecie')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>

        <?=
        \yii\bootstrap\Tabs::widget(
                [
                    'encodeLabels' => false,
                    'items' => [ [
                            'label' => 'Não Identificado: '.($model->MorfoEspecie?$model->MorfoEspecie:"Sem Morfo Espécie"),
                            'content' => $this->blocks['main'],
                            'active' => true,
                        ],]
                ]
        );
        ?>
        <hr/>

        <?=
        Html::submitButton('<span class="glyphicon glyphicon-check"></span> ' . ($model->isNewRecord ? 'Criar' : 'Salvar'), ['class' => $model->isNewRecord ?
                    'btn btn-primary' : 'btn btn-primary'])
        ?>

        <?= Html::a('Cancelar', \yii\helpers\Url::previous(), ['class' => 'btn btn-default']) ?>
<?php ActiveForm::end(); ?>

    </div>

</div>
