<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/**
 * @var yii\web\View $this
 * @var app\models\TipoOrganismo $model
 */
$this->title = 'Tipo de Organismo: ' . $model->label . '';
$this->params['breadcrumbs'][] = ['label' => 'Tipos de Organismo', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->label, 'url' => ['view', 'idTipoOrganismo' => $model->idTipoOrganismo]];
$this->params['breadcrumbs'][] = 'Detalhes';
?>
<div class="tipo-organismo-view">

    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> Editar', ['update', 'idTipoOrganismo' => $model->idTipoOrganismo], ['class' => 'btn btn-info'])
        ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> Novo Tipo de Organismo', ['create'], ['class' => 'btn
        btn-success']) ?>
    </p>

    <p class='pull-right'>
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> Lista', ['index'], ['class' => 'btn btn-default']) ?>
    </p><div class='clearfix'></div> 


    <h3>
        <?= $model->label ?>    </h3>


    <?php $this->beginBlock('app\models\TipoOrganismo'); ?>

    <?php
    echo DetailView::widget([
        'model' => $model,
        'attributes' => [
            'idTipoOrganismo',
            'Nome',
            'Descricao:ntext',
        ],
    ]);
    ?>

    <hr/>

    <?php
    echo Html::a('<span class="glyphicon glyphicon-trash"></span> Deletar', ['delete', 'idTipoOrganismo' => $model->idTipoOrganismo], [
        'class' => 'btn btn-danger',
        'data-confirm' => Yii::t('app', 'Tem certeza que quer deletar esse item?'),
        'data-method' => 'post',
    ]);
    ?>

    <?php $this->endBlock(); ?>



    <?php $this->beginBlock('Especies'); ?>
    <p class='pull-right'>
        <?=
        \yii\helpers\Html::a(
                '<span class="glyphicon glyphicon-list"></span> Listar todas espécies', ['especie/index'], ['class' => 'btn text-muted btn-xs']
        )
        ?>
        <?=
        \yii\helpers\Html::a(
                '<span class="glyphicon glyphicon-plus"></span> Nova Espécie', ['especie/create', 'Especy' => ['idTipo_Organismo' => $model->idTipoOrganismo]], ['class' => 'btn btn-success btn-xs']
        )
        ?>
    </p><div class='clearfix'></div>
    <?php Pjax::begin(['id' => 'pjax-Especies', 'linkSelector' => '#pjax-Especies ul.pagination a']) ?>
    <?=
    \yii\grid\GridView::widget([
        'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getEspecies(), 'pagination' => ['pageSize' => 10]]),
        'columns' => [ 'idEspecie',
            'NomeCientifico',
            'NomeComum',
            'Descricao:ntext',
// generated by schmunk42\giiant\crud\providers\RelationProvider::columnFormat
            [
                "class" => yii\grid\DataColumn::className(),
                "attribute" => "idGenero",
                "value" => function($model)
                {
                    if ($rel = $model->getIdGenero0()->one())
                    {
                        return yii\helpers\Html::a($rel->label, ["genero/view", 'idGenero' => $rel->idGenero,], ["data-pjax" => 0]);
                    } else
                    {
                        return '';
                    }
                },
                        "format" => "raw",
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{view} {update}',
                        'contentOptions' => ['nowrap' => 'nowrap'],
                        'urlCreator' => function($action, $model, $key, $index)
                {
                    // using the column name as key, not mapping to 'id' like the standard generator
                    $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                    $params[0] = 'especie' . '/' . $action;
                    return \yii\helpers\Url::toRoute($params);
                },
                        'buttons' => [
                        ],
                        'controller' => 'especie'
                    ],]
            ]);
            ?>
            <?php Pjax::end() ?>
            <?php $this->endBlock() ?>


            <?php $this->beginBlock('IdDescritores'); ?>
            <p class='pull-right'>
                <?=
                \yii\helpers\Html::a(
                        '<span class="glyphicon glyphicon-list"></span> Listar todos descritores', ['descritor/index'], ['class' => 'btn text-muted btn-xs']
                )
                ?>
                <?=
                \yii\helpers\Html::a(
                        '<span class="glyphicon glyphicon-plus"></span> Novo Descritor', ['descritor/create', 'IdDescritor' => ['idDescritor' => $model->idTipoOrganismo]], ['class' => 'btn btn-success btn-xs']
                )
                ?>
            </p><div class='clearfix'></div>
            <?php Pjax::begin(['id' => 'pjax-IdDescritores', 'linkSelector' => '#pjax-IdDescritores ul.pagination a']) ?>
            <?=
            \yii\grid\GridView::widget([
                'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getTipoOrganismoHasDescritores(), 'pagination' => ['pageSize' => 10]]),
                'columns' => [
                    'idDescritor0.Nome',
                    'idDescritor0.idTipoDado0.Tipo',
                    'idDescritor0.idTipoDescritor0.Tipo',
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{view} {delete}',
                        'contentOptions' => ['nowrap' => 'nowrap'],
                        'urlCreator' => function($action, $model, $key, $index)
                {
                    // using the column name as key, not mapping to 'id' like the standard generator
                    $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                    $params[0] = 'tipo-organismo-has-descritor' . '/' . $action;
                    return \yii\helpers\Url::toRoute($params);
                },
                        'buttons' => [
                            'delete' => function ($url, $model)
                            {
                                return Html::a('<span class="glyphicon glyphicon-remove"></span>', $url, [
                                            'class' => 'text-danger',
                                            'title' => Yii::t('yii', 'Remove'),
                                            'data-confirm' => Yii::t('yii', 'Are you sure you want to delete the related item?'),
                                            'data-method' => 'post',
                                            'data-pjax' => '0',
                                ]);
                            },
                                    'view' => function ($url, $model)
                            {
                                return Html::a(
                                                '<span class="glyphicon glyphicon-cog"></span>', $url, [
                                            'data-title' => Yii::t('yii', 'View Pivot Record'),
                                            'data-toggle' => 'tooltip',
                                            'data-pjax' => '0',
                                            'class' => 'text-muted'
                                                ]
                                );
                            },
                                ],
                                'controller' => 'tipo-organismo-has-descritor'
                            ],]
                    ]);
                    ?>
                    <?php Pjax::end() ?>
                    <?php $this->endBlock() ?>


                    <?=
                    \yii\bootstrap\Tabs::widget(
                            [
                                'id' => 'relation-tabs',
                                'encodeLabels' => false,
                                'items' => [ [
                                        'label' => '<span class="glyphicon glyphicon-asterisk"></span> Tipo de Organismo',
                                        'content' => $this->blocks['app\models\TipoOrganismo'],
                                        'active' => true,
                                    ], [
                                        'label' => '<small><span class="glyphicon glyphicon-paperclip"></span> Espécies</small>',
                                        'content' => $this->blocks['Especies'],
                                        'active' => false,
                                    ], [
                                        'label' => '<small><span class="glyphicon glyphicon-paperclip"></span> Descritores</small>',
                                        'content' => $this->blocks['IdDescritores'],
                                        'active' => false,
                                    ],]
                            ]
                    );
                    ?></div>
