<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/**
* @var yii\web\View $this
* @var app\models\Atributo $model
*/

$this->title = 'Atributo View ' . $model->idAtributo . '';
$this->params['breadcrumbs'][] = ['label' => 'Atributos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->label, 'url' => ['view', 'idAtributo' => $model->idAtributo]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="atributo-view">

    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> Edit', ['update', 'idAtributo' => $model->idAtributo],
        ['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> New Atributo', ['create'], ['class' => 'btn
        btn-success']) ?>
    </p>

        <p class='pull-right'>
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> List', ['index'], ['class'=>'btn btn-default']) ?>
    </p><div class='clearfix'></div> 

    
    <h3>
        <?= $model->label ?>    </h3>


    <?php $this->beginBlock('app\models\Atributo'); ?>

    <?php echo DetailView::widget([
    'model' => $model,
    'attributes' => [
    			'idAtributo',
			'Nome',
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
[
    'format'=>'html',
    'attribute'=>'idTipoDado',
    'value' => ($model->getIdTipoDado0()->one() ? Html::a($model->getIdTipoDado0()->one()->label, ['tipo-dado/view', 'idTipoDado' => $model->getIdTipoDado0()->one()->idTipoDado,]) : '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\crud\providers\RelationProvider::attributeFormat
[
    'format'=>'html',
    'attribute'=>'idTipoAtributo',
    'value' => ($model->getIdTipoAtributo0()->one() ? Html::a($model->getIdTipoAtributo0()->one()->label, ['tipo-atributo/view', 'idTipoAtributo' => $model->getIdTipoAtributo0()->one()->idTipoAtributo,]) : '<span class="label label-warning">?</span>'),
],
			'Descricao:ntext',
    ],
    ]); ?>

    <hr/>

    <?php echo Html::a('<span class="glyphicon glyphicon-trash"></span> Delete', ['delete', 'idAtributo' => $model->idAtributo],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => Yii::t('app', 'Are you sure to delete this item?'),
    'data-method' => 'post',
    ]); ?>

    <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('IdTipoOrganismos'); ?>
<p class='pull-right'>
  <?= \yii\helpers\Html::a(
            '<span class="glyphicon glyphicon-list"></span> List All Id Tipo Organismos',
            ['tipo-organismo/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= \yii\helpers\Html::a(
            '<span class="glyphicon glyphicon-plus"></span> New Id Tipo Organismo',
            ['tipo-organismo/create', 'IdTipoOrganismo'=>['idTipoOrganismo'=>$model->idAtributo]],
            ['class'=>'btn btn-success btn-xs']
        ) ?>
  <?= \yii\helpers\Html::a(
            '<span class="glyphicon glyphicon-link"></span> Attach Id Tipo Organismo', ['tipo-organismo-has-atributo/create', 'TipoOrganismoHasAtributo'=>['idAtributo'=>$model->idAtributo]],
            ['class'=>'btn btn-info btn-xs']
        ) ?>
</p><div class='clearfix'></div>
<?php Pjax::begin(['id'=>'pjax-IdTipoOrganismos','linkSelector'=>'#pjax-IdTipoOrganismos ul.pagination a']) ?>
<?= \yii\grid\GridView::widget([
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getTipoOrganismoHasAtributos(), 'pagination' => ['pageSize' => 10]]),
    'columns' => [			'idTipoOrganismo',
[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {delete}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'tipo-organismo-has-atributo' . '/' . $action;
        return \yii\helpers\Url::toRoute($params);
    },
    'buttons'    => [
        'delete' => function ($url, $model) {
                return Html::a('<span class="glyphicon glyphicon-remove"></span>', $url, [
                    'class' => 'text-danger',
                    'title' => Yii::t('yii', 'Remove'),
                    'data-confirm' => Yii::t('yii', 'Are you sure you want to delete the related item?'),
                    'data-method' => 'post',
                    'data-pjax' => '0',
                ]);
            },
'view' => function ($url, $model) {
                return Html::a(
                    '<span class="glyphicon glyphicon-cog"></span>',
                    $url,
                    [
                        'data-title'  => Yii::t('yii', 'View Pivot Record'),
                        'data-toggle' => 'tooltip',
                        'data-pjax'   => '0',
                        'class'        => 'text-muted'
                    ]
                );
            },
    ],
    'controller' => 'tipo-organismo-has-atributo'
],]
]);?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?=
    \yii\bootstrap\Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<span class="glyphicon glyphicon-asterisk"></span> Atributo',
    'content' => $this->blocks['app\models\Atributo'],
    'active'  => true,
],[
    'label'   => '<small><span class="glyphicon glyphicon-paperclip"></span> Id Tipo Organismos</small>',
    'content' => $this->blocks['IdTipoOrganismos'],
    'active'  => false,
], ]
                 ]
    );
    ?></div>
